### ISSUE TITLE
admin screen broken

### ISSUE THREAD

**Issue by zzamboni** [binaryage/drydrop#2] opened 2009-09-30 14:12 UTC
Hi again,

Before I broke my install with the issue I reported previously, I noticed the admin screen of my application was not being displayed properly - it looked as if the CSS files were not being loaded properly - I could see the contents, but without any styling.

I was wondering if maybe it's related to the GitHub move? Everything looked fine last week.

**Comment by darwin** [comment] 2009-09-30 15:52
If you look at code for main request handler: 
http://github.com/darwin/drydrop/blob/master/dryapp/drydrop_handler.py#L275

Drydrop is first trying to resolve request using your site.yaml rules. If it is not successful, it runs system dispatch routine. Admin section is served using system dispatch, but you have to not override it by your site.

Or maybe there is some bug :-( Hard to say ...

**Comment by darwin** [comment] 2009-09-30 16:06
I just tried drydropsample.appspot.com/admin

And I can confirm admin section is broken. I cannot even log in. Something was changed on Google side so it is broken now. I will probably get to fix during weekend.

**Comment by darwin** [comment] 2009-09-30 16:06
Main site still works for me, so it is issue with something in admin section.

**Comment by darwin** [comment] 2009-10-03 17:15
I gave it few minutes and the reason of broken admin screen is github beahvior.

If you request non-existent file in repo (for example http://github.com/darwin/web-app-theme/raw/master/abc/README.md) it returns with 200 OK and page saying "Repository temporarily unavailable". DryDrop just takes this as a real content.

That is also reason why admin screen is broken. Site.yaml dispatch is working and drydrop uses these buggy files in place of admin css and js files.

The reason why it works this way was enabling you to override admin.css and other files by your github repo if you want...

**Comment by darwin** [comment] 2009-10-03 17:49
detect bogus status404 pages from github and treat them as real 404 pages (closed by b68d13fddd1380a6cd73d596124ede979e36e87f)

**Closed as completed by darwin** 2009-10-03 17:49 UTC

**Comment by zzamboni** [comment] 2009-10-03 18:45
Hi - thanks. Unfortunately, this does not seem to have solved the problem for me. I still see the admin screen broken (I'm not getting the GitHub "repository unavailable" any more, though). Looking at the logs, I am not finding the "bogus 404" message you added in the latest patch.

Any ideas?
Thanks for your help!

**Comment by darwin** [comment] 2009-10-03 18:52
have you uploaded latest sources and cleared Resources via appengine console?

give me url which is failing for you, so I can investigate github's response

**Comment by jacqueminv** [comment] 2009-10-05 12:07
Hi all,

Unfortunately the same issue for me here: http://scbcd-study-guide.appspot.com/
I have pulled the last version of drydrop...

Thanks

**Comment by zzamboni** [comment] 2009-10-05 12:15
@darwin, do you know if there's an easy way to clear all the Resources? Deleting them a screenful at a time is quite painful, but I haven't found a better way...

**Comment by zzamboni** [comment] 2009-10-07 09:39
Just to confirm that this issue has been fixed. Because the javascript files were apparently not properly cached, the "Flush resource cache" button in the admin screen didn't work, but I was able to manually flush the cache by going to `/admin/flusher?command=go` in my domain. Now everything works fine.

Thanks for all your help!
